# Generated by Django 4.2.5 on 2023-09-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0002_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
