# Generated by Django 4.2.5 on 2023-09-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0004_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cpassword',
        ),
    ]
