# Generated by Django 4.2.5 on 2023-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
