# Generated by Django 4.2.5 on 2023-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0015_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_customer',
            new_name='is_Customer',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_seller',
            new_name='is_Dietitian',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_Doctor',
            field=models.BooleanField(default=False),
        ),
    ]
