# Generated by Django 4.2.5 on 2023-09-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0016_rename_is_customer_customuser_is_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Dietitian'), (3, 'Doctor')], default=1, null=True),
        ),
    ]
