# Generated by Django 4.2.5 on 2023-09-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0017_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
