# Generated by Django 4.2.5 on 2023-09-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0018_remove_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_Customer',
            field=models.BooleanField(default=True),
        ),
    ]
