# Generated by Django 4.2.5 on 2023-09-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0019_alter_customuser_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_Customer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
