# Generated by Django 4.2.5 on 2023-10-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0028_alter_userprofile_age_alter_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
