# Generated by Django 4.2.5 on 2023-11-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0030_alter_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='available_timings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
