# Generated by Django 4.2.5 on 2023-11-02 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0032_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='booked_by',
            field=models.ManyToManyField(blank=True, related_name='booked_doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
