# Generated by Django 4.2.5 on 2023-11-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0034_remove_booking_slot_datetime_booking_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
