# Generated by Django 4.2.5 on 2023-11-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0036_foodintake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodintake',
            old_name='intake_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='foodintake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct.userprofile'),
        ),
    ]
