# Generated by Django 4.2.5 on 2023-11-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0038_userprofile_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
