# Generated by Django 4.2.5 on 2023-11-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0040_exerciselog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselog',
            old_name='duration_minutes',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise_name',
            field=models.CharField(max_length=255),
        ),
    ]
