# Generated by Django 4.2.5 on 2023-11-06 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0041_rename_duration_minutes_exerciselog_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
