# Generated by Django 4.2.5 on 2023-11-06 03:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0042_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietitianprofile',
            name='available_timings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DietitianBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=datetime.date(2023, 1, 1))),
                ('dietitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct.dietitianprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
