# Generated by Django 4.2.5 on 2023-11-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0045_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='dietitian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ct.dietitianprofile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ct.doctorprofile'),
        ),
    ]
