# Generated by Django 4.2.5 on 2023-11-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0048_alter_feedback_options_alter_feedback_dietitian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Active', 'Active'), ('Very Active', 'Very Active')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bmr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
