# Generated by Django 4.2.5 on 2023-11-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0053_alter_timeslot_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='dietitian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ct.dietitianprofile'),
            preserve_default=False,
        ),
    ]
