# Generated by Django 4.2.5 on 2023-11-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0056_alter_dietitianbooking_dietitian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='dietitian',
        ),
    ]
