# Generated by Django 4.2.5 on 2023-11-23 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0057_remove_timeslot_dietitian'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietitianRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('review', models.TextField()),
                ('dietitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ct.dietitianprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
