# Generated by Django 4.2.5 on 2023-11-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0058_dietitianrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietitianrating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1),
        ),
    ]
