# Generated by Django 4.2.5 on 2023-11-30 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0063_alter_timeslot_dietitian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='dietitian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
