# Generated by Django 4.2.5 on 2023-11-30 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0064_alter_timeslot_dietitian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
