# Generated by Django 4.2.5 on 2023-12-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0065_alter_doctorslot_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietitianbooking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dietitianbooking',
            name='session',
            field=models.CharField(default='afternoon', max_length=255),
        ),
        migrations.AddField(
            model_name='dietitianbooking',
            name='time',
            field=models.CharField(default='09:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='dietitianbooking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
