# Generated by Django 4.2.5 on 2023-12-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0068_alter_dietitianbooking_dietitian'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietitianbooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
