# Generated by Django 4.2.5 on 2024-03-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0073_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
